<?php declare(strict_types=1); ?>
<?php
$statusValue = (string) ($employee['employee_status'] ?? 'draft');
$isArchived = (($employee['archived_at'] ?? null) !== null) || $statusValue === 'archived';
?>
<div class="card content-card mb-4"><div class="card-body p-4 d-flex flex-column flex-md-row justify-content-between align-items-md-center gap-3"><div><h5 class="mb-1">Archive Employee Record</h5><p class="text-muted mb-0">Move this employee out of the active directory while preserving profile and activity history.</p></div><div class="d-flex gap-2"><a href="<?= e(url('/employees/' . $employee['id'] . '/history')); ?>" class="btn btn-outline-secondary">View History</a><a href="<?= e(url('/employees/' . $employee['id'])); ?>" class="btn btn-outline-secondary">Back to Profile</a></div></div></div>

<div class="row g-4">
    <div class="col-lg-4"><div class="card content-card h-100"><div class="card-body p-4"><h5 class="mb-3">Employee Snapshot</h5><div class="mb-2"><strong>Name:</strong><br><?= e(trim((string) (($employee['first_name'] ?? '') . ' ' . ($employee['middle_name'] ?? '') . ' ' . ($employee['last_name'] ?? '')))); ?></div><div class="mb-2"><strong>Code:</strong><br><?= e((string) ($employee['employee_code'] ?? '—')); ?></div><div class="mb-2"><strong>Department:</strong><br><?= e((string) (($employee['department_name'] ?? '') !== '' ? $employee['department_name'] : '—')); ?></div><div class="mb-2"><strong>Designation:</strong><br><?= e((string) (($employee['designation_name'] ?? '') !== '' ? $employee['designation_name'] : '—')); ?></div><div class="mb-2"><strong>Current Status:</strong><br><span class="badge <?= $statusValue === 'archived' ? 'text-bg-dark' : ($statusValue === 'active' ? 'text-bg-success' : 'text-bg-secondary'); ?>"><?= e(ucwords(str_replace('_', ' ', $statusValue))); ?></span></div><?php if (($employee['archived_at'] ?? null) !== null): ?><div><strong>Archived At:</strong><br><?= e((string) $employee['archived_at']); ?></div><?php endif; ?></div></div></div>
    <div class="col-lg-8"><div class="card content-card"><div class="card-body p-4"><?php if ($isArchived): ?><div class="alert alert-secondary mb-0">This employee record is already archived. You can still review the full timeline from the history page.</div><?php else: ?><div class="alert alert-warning"><strong>Heads up:</strong> archived employees are removed from the active employee directory, but their profile and history stay available for review.</div><form method="post" action="<?= e(url('/employees/' . $employee['id'] . '/archive')); ?>"><?= csrf_field(); ?><div class="mb-3"><label class="form-label">Archive Remarks</label><textarea name="remarks" class="form-control" rows="4" maxlength="255" placeholder="Optional note for why this employee is being archived."><?= e((string) old('remarks', '')); ?></textarea><div class="form-text">This note will be stored in the employee status history.</div></div><button type="submit" class="btn btn-danger">Archive Employee</button></form><?php endif; ?></div></div></div>
</div>