<?php declare(strict_types=1); ?>
<?php require base_path('app/Views/partials/settings-nav.php'); ?>
<div class="row g-4">
    <div class="col-xl-4">
        <div class="card content-card h-100"><div class="card-body p-4"><h5 class="mb-2">Assign Work Schedule</h5><p class="text-muted small mb-4">Create one schedule period per employee. Overlapping assignment dates are blocked to keep attendance shift resolution predictable.</p><form method="post" action="<?= e(url('/settings/attendance/assignments')); ?>"><?= csrf_field(); ?><div class="mb-3"><label class="form-label">Employee *</label><select name="employee_id" class="form-select" required><option value="">Select employee</option><?php foreach (($employeeOptions ?? []) as $employee): ?><option value="<?= e((string) $employee['id']); ?>" <?= (string) old('employee_id', '') === (string) $employee['id'] ? 'selected' : ''; ?>><?= e((string) $employee['name']); ?></option><?php endforeach; ?></select></div><div class="mb-3"><label class="form-label">Work Schedule *</label><select name="work_schedule_id" class="form-select" required><option value="">Select schedule</option><?php foreach (($scheduleOptions ?? []) as $schedule): ?><option value="<?= e((string) $schedule['id']); ?>" <?= (string) old('work_schedule_id', '') === (string) $schedule['id'] ? 'selected' : ''; ?>><?= e((string) $schedule['name']); ?></option><?php endforeach; ?></select></div><div class="mb-3"><label class="form-label">Shift Override</label><select name="shift_id" class="form-select"><option value="">Schedule default (no override)</option><?php foreach (($shiftOptions ?? []) as $shift): ?><option value="<?= e((string) $shift['id']); ?>" <?= (string) old('shift_id', '') === (string) $shift['id'] ? 'selected' : ''; ?>><?= e((string) $shift['name']); ?></option><?php endforeach; ?></select><div class="form-text">Optional. Leave blank to use the selected schedule's daily shifts.</div></div><div class="row g-3"><div class="col-md-6"><label class="form-label">Effective From *</label><input type="date" name="effective_from" class="form-control" value="<?= e((string) old('effective_from', date('Y-m-d'))); ?>" required></div><div class="col-md-6"><label class="form-label">Effective To</label><input type="date" name="effective_to" class="form-control" value="<?= e((string) old('effective_to', '')); ?>"></div><div class="col-12"><label class="form-label">Status</label><select name="status" class="form-select"><?php foreach (($assignmentStates ?? []) as $value => $label): ?><option value="<?= e((string) $value); ?>" <?= (string) old('status', 'active') === (string) $value ? 'selected' : ''; ?>><?= e((string) $label); ?></option><?php endforeach; ?></select></div></div><button type="submit" class="btn btn-primary w-100 mt-4">Save Schedule Assignment</button></form></div></div>
    </div>
    <div class="col-xl-8">
        <div class="card content-card"><div class="card-body p-4"><div class="d-flex flex-column flex-md-row justify-content-between align-items-md-center gap-3 mb-4"><div><h5 class="mb-1">Schedule Assignments</h5><p class="text-muted mb-0">Review which employees are currently mapped to work schedules and direct shift overrides.</p></div><form method="get" action="<?= e(url('/settings/attendance/assignments')); ?>" class="d-flex flex-column flex-md-row gap-2"><input type="text" name="q" class="form-control" placeholder="Search employees or schedules..." value="<?= e((string) ($search ?? '')); ?>"><select name="status" class="form-select"><?php foreach (($statusOptions ?? []) as $value => $label): ?><option value="<?= e((string) $value); ?>" <?= (string) ($status ?? 'all') === (string) $value ? 'selected' : ''; ?>><?= e((string) $label); ?></option><?php endforeach; ?></select><button type="submit" class="btn btn-outline-secondary">Search</button></form></div><div class="d-flex justify-content-end mb-3"><span class="badge text-bg-light"><?= e((string) count($assignments ?? [])); ?> result(s)</span></div><?php if (($assignments ?? []) === []): ?><div class="empty-state">No schedule assignments matched the selected filters.</div><?php else: ?><div class="table-responsive"><table class="table align-middle mb-0"><thead><tr><th>Employee</th><th>Schedule</th><th>Shift Override</th><th>Effective From</th><th>Effective To</th><th>Status</th></tr></thead><tbody><?php foreach (($assignments ?? []) as $row): ?><tr><td><div class="fw-semibold"><?= e((string) $row['employee_name']); ?></div></td><td><?= e((string) $row['schedule_name']); ?></td><td><?= e((string) $row['shift_name']); ?></td><td><?= e((string) $row['effective_from']); ?></td><td><?= e((string) $row['effective_to']); ?></td><td><span class="badge <?= (string) $row['status'] === 'active' ? 'text-bg-success' : 'text-bg-secondary'; ?>"><?= e((string) ucfirst((string) $row['status'])); ?></span></td></tr><?php endforeach; ?></tbody></table></div><?php endif; ?></div></div>
    </div>
</div>