<?php declare(strict_types=1); ?>
<?php require base_path('app/Views/partials/settings-nav.php'); ?>
<div class="d-flex flex-wrap gap-2 mb-4">
    <a href="<?= e(url('/settings/attendance/records')); ?>" class="btn btn-primary btn-sm">Open Attendance Register</a>
    <a href="<?= e(url('/settings/attendance/assignments')); ?>" class="btn btn-outline-primary btn-sm">Review Assignments</a>
</div>
<div class="row g-3 mb-4">
    <div class="col-md-6 col-xl-2"><div class="card content-card h-100"><div class="card-body"><div class="text-muted small">Records Today</div><div class="display-6 fw-semibold"><?= e((string) ($attendance['today_total'] ?? 0)); ?></div></div></div></div>
    <div class="col-md-6 col-xl-2"><div class="card content-card h-100"><div class="card-body"><div class="text-muted small">Present</div><div class="display-6 fw-semibold"><?= e((string) ($attendance['today_present'] ?? 0)); ?></div></div></div></div>
    <div class="col-md-6 col-xl-2"><div class="card content-card h-100"><div class="card-body"><div class="text-muted small">Absent</div><div class="display-6 fw-semibold"><?= e((string) ($attendance['today_absent'] ?? 0)); ?></div></div></div></div>
    <div class="col-md-6 col-xl-2"><div class="card content-card h-100"><div class="card-body"><div class="text-muted small">Late</div><div class="display-6 fw-semibold"><?= e((string) ($attendance['today_late'] ?? 0)); ?></div></div></div></div>
    <div class="col-md-6 col-xl-4"><div class="card content-card h-100"><div class="card-body"><div class="text-muted small">Active Schedule Assignments</div><div class="display-6 fw-semibold"><?= e((string) ($attendance['active_assignments'] ?? 0)); ?></div></div></div></div>
</div>
<div class="card content-card"><div class="card-body p-4"><h5 class="mb-3">Recent Attendance Records</h5><?php if ((($attendance['recent_records'] ?? [])) === []): ?><div class="empty-state">No attendance records have been captured yet.</div><?php else: ?><div class="table-responsive"><table class="table align-middle mb-0"><thead><tr><th>Employee</th><th>Date</th><th>Status</th><th>Shift</th><th>Clock In/Out</th><th>Source</th></tr></thead><tbody><?php foreach (($attendance['recent_records'] ?? []) as $row): ?><tr><td><div class="fw-semibold"><?= e((string) $row['employee_name']); ?></div><div class="small text-muted"><?= e((string) $row['employee_code']); ?></div></td><td><?= e((string) $row['attendance_date']); ?></td><td><span class="badge text-bg-<?= e((string) $row['color_class']); ?>"><?= e((string) $row['status_name']); ?></span><?php if ((int) ($row['minutes_late'] ?? 0) > 0): ?><div class="small text-muted mt-1">Late by <?= e((string) $row['minutes_late']); ?> min</div><?php endif; ?></td><td><?= e((string) $row['shift_name']); ?></td><td><div class="small">In: <?= e((string) (($row['clock_in_time'] ?? null) !== null ? $row['clock_in_time'] : '—')); ?></div><div class="small">Out: <?= e((string) (($row['clock_out_time'] ?? null) !== null ? $row['clock_out_time'] : '—')); ?></div></td><td><?= e(ucwords((string) $row['source'])); ?></td></tr><?php endforeach; ?></tbody></table></div><?php endif; ?></div></div>