<?php declare(strict_types=1); ?>
<?php require base_path('app/Views/partials/leave-nav.php'); ?>
<div class="row g-3 mb-4">
    <div class="col-md-6 col-xl-3"><div class="card content-card h-100"><div class="card-body"><div class="text-muted small">Calendar Month</div><div class="display-6 fw-semibold"><?= e((string) ($monthLabel ?? '')); ?></div><div class="small text-muted mt-2"><?= e((string) ($scope['label'] ?? '')); ?></div></div></div></div>
    <div class="col-md-6 col-xl-3"><div class="card content-card h-100"><div class="card-body"><div class="text-muted small">Visible Requests</div><div class="display-6 fw-semibold"><?= e((string) ($summary['total'] ?? 0)); ?></div></div></div></div>
    <div class="col-md-6 col-xl-3"><div class="card content-card h-100"><div class="card-body"><div class="text-muted small">Approved</div><div class="display-6 fw-semibold"><?= e((string) ($summary['approved'] ?? 0)); ?></div></div></div></div>
    <div class="col-md-6 col-xl-3"><div class="card content-card h-100"><div class="card-body"><div class="text-muted small">Pending</div><div class="display-6 fw-semibold"><?= e((string) ($summary['pending'] ?? 0)); ?></div></div></div></div>
</div>

<div class="card content-card mb-4"><div class="card-body p-4"><div class="d-flex flex-column flex-lg-row justify-content-between gap-3 mb-4"><div><h5 class="mb-1">Leave Calendar</h5><p class="text-muted mb-0">Review overlapping leave requests across the selected month.</p></div><div class="d-flex gap-2"><a href="<?= e(url('/leave/calendar?month=' . ($previousMonth ?? date('Y-m')))); ?>" class="btn btn-outline-secondary btn-sm">&larr; Previous</a><a href="<?= e(url('/leave/calendar?month=' . date('Y-m'))); ?>" class="btn btn-outline-light border btn-sm">Current</a><a href="<?= e(url('/leave/calendar?month=' . ($nextMonth ?? date('Y-m')))); ?>" class="btn btn-outline-secondary btn-sm">Next &rarr;</a></div></div><form method="get" action="<?= e(url('/leave/calendar')); ?>" class="row g-3 align-items-end"><div class="col-lg-4"><label class="form-label">Search</label><input type="text" name="q" class="form-control" placeholder="Employee, department, company, or leave type..." value="<?= e((string) ($search ?? '')); ?>"></div><div class="col-md-3 col-lg-2"><label class="form-label">Month</label><input type="month" name="month" class="form-control" value="<?= e((string) ($month ?? date('Y-m'))); ?>"></div><div class="col-md-3 col-lg-2"><label class="form-label">Status</label><select name="status" class="form-select"><option value="approved" <?= (string) ($status ?? 'approved') === 'approved' ? 'selected' : ''; ?>>Approved</option><option value="all" <?= (string) ($status ?? 'approved') === 'all' ? 'selected' : ''; ?>>All statuses</option><?php foreach (['submitted' => 'Submitted', 'pending_manager' => 'Pending Manager', 'pending_hr' => 'Pending HR', 'rejected' => 'Rejected', 'cancelled' => 'Cancelled', 'withdrawn' => 'Withdrawn'] as $value => $label): ?><option value="<?= e($value); ?>" <?= (string) ($status ?? 'approved') === $value ? 'selected' : ''; ?>><?= e($label); ?></option><?php endforeach; ?></select></div><div class="col-md-3 col-lg-2"><label class="form-label">Leave Type</label><select name="leave_type_id" class="form-select"><option value="0">All leave types</option><?php foreach (($leaveTypes ?? []) as $leaveType): ?><option value="<?= e((string) $leaveType['id']); ?>" <?= (string) ($leaveTypeId ?? 0) === (string) $leaveType['id'] ? 'selected' : ''; ?>><?= e((string) $leaveType['name']); ?></option><?php endforeach; ?></select></div><div class="col-lg-2 d-flex gap-2"><button type="submit" class="btn btn-outline-secondary w-100">Filter</button><a href="<?= e(url('/leave/calendar')); ?>" class="btn btn-outline-light border w-100">Reset</a></div></form></div></div>

<div class="card content-card mb-4"><div class="card-body p-3 p-lg-4"><?php if (($weeks ?? []) === []): ?><div class="empty-state">No calendar data is available for the selected month.</div><?php else: ?><div class="table-responsive"><table class="table table-bordered align-top mb-0"><thead><tr><?php foreach (['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun'] as $dayLabel): ?><th class="text-center small text-muted"><?= e($dayLabel); ?></th><?php endforeach; ?></tr></thead><tbody><?php foreach ($weeks as $week): ?><tr><?php foreach ($week as $day): ?><td class="p-2 <?= ($day['in_month'] ?? false) ? '' : 'bg-light'; ?>"><div class="d-flex justify-content-between align-items-center mb-2"><span class="small fw-semibold"><?= e((string) $day['day_number']); ?></span><?php if (($day['is_today'] ?? false)): ?><span class="badge text-bg-dark">Today</span><?php endif; ?></div><?php if (($day['events'] ?? []) !== []): ?><div class="d-grid gap-2"><?php foreach ($day['events'] as $event): ?><a href="<?= e(url('/leave/requests/' . $event['id'])); ?>" class="text-decoration-none"><div class="border rounded p-2 small"><div class="fw-semibold text-dark"><?= e((string) $event['employee_name']); ?></div><div class="text-muted"><?= e((string) $event['leave_type_name']); ?></div><div><span class="badge <?= (string) $event['status'] === 'approved' ? 'text-bg-success' : ((string) $event['status'] === 'rejected' ? 'text-bg-danger' : 'text-bg-warning'); ?> mt-1"><?= e(ucwords(str_replace('_', ' ', (string) $event['status']))); ?></span></div></div></a><?php endforeach; ?></div><?php else: ?><div class="small text-muted">No leave</div><?php endif; ?></td><?php endforeach; ?></tr><?php endforeach; ?></tbody></table></div><?php endif; ?></div></div>

<div class="card content-card"><div class="card-body p-4"><h5 class="mb-3">Requests in View</h5><?php if (($calendarRequests ?? []) === []): ?><div class="empty-state">No leave requests overlap the selected month.</div><?php else: ?><div class="table-responsive"><table class="table align-middle mb-0"><thead><tr><th>Employee</th><th>Leave Type</th><th>Dates</th><th>Status</th></tr></thead><tbody><?php foreach ($calendarRequests as $leaveRequest): ?><tr><td><div class="fw-semibold"><?= e((string) $leaveRequest['employee_name']); ?></div><div class="small text-muted"><?= e((string) $leaveRequest['employee_code']); ?></div></td><td><?= e((string) $leaveRequest['leave_type_name']); ?></td><td><?= e((string) $leaveRequest['start_date']); ?> → <?= e((string) $leaveRequest['end_date']); ?></td><td><span class="badge <?= (string) $leaveRequest['status'] === 'approved' ? 'text-bg-success' : ((string) $leaveRequest['status'] === 'rejected' ? 'text-bg-danger' : 'text-bg-warning'); ?>"><?= e(ucwords(str_replace('_', ' ', (string) $leaveRequest['status']))); ?></span></td></tr><?php endforeach; ?></tbody></table></div><?php endif; ?></div></div>