<?php declare(strict_types=1); ?>
<?php require base_path('app/Views/partials/leave-nav.php'); ?>
<div class="row g-3 mb-4">
    <div class="col-md-6 col-xl-3"><div class="card content-card h-100"><div class="card-body"><div class="text-muted small">Requests</div><div class="display-6 fw-semibold"><?= e((string) ($summary['total'] ?? 0)); ?></div><div class="small text-muted mt-2"><?= e((string) ($scope['label'] ?? '')); ?></div></div></div></div>
    <div class="col-md-6 col-xl-3"><div class="card content-card h-100"><div class="card-body"><div class="text-muted small">Pending</div><div class="display-6 fw-semibold"><?= e((string) ($summary['pending'] ?? 0)); ?></div></div></div></div>
    <div class="col-md-6 col-xl-3"><div class="card content-card h-100"><div class="card-body"><div class="text-muted small">Approved</div><div class="display-6 fw-semibold"><?= e((string) ($summary['approved'] ?? 0)); ?></div></div></div></div>
    <div class="col-md-6 col-xl-3"><div class="card content-card h-100"><div class="card-body"><div class="text-muted small">Rejected / Closed</div><div class="display-6 fw-semibold"><?= e((string) ((int) ($summary['rejected'] ?? 0) + (int) ($summary['closed'] ?? 0))); ?></div></div></div></div>
</div>

<div class="card content-card mb-4"><div class="card-body p-4"><form method="get" action="<?= e(url('/leave/requests')); ?>" class="row g-3 align-items-end"><div class="col-lg-6"><label class="form-label">Search</label><input type="text" name="q" class="form-control" placeholder="Employee, department, leave type, or request reason..." value="<?= e((string) ($search ?? '')); ?>"></div><div class="col-md-3 col-lg-2"><label class="form-label">Status</label><select name="status" class="form-select"><option value="all">All statuses</option><?php foreach (['draft' => 'Draft', 'submitted' => 'Submitted', 'pending_manager' => 'Pending Manager', 'pending_hr' => 'Pending HR', 'approved' => 'Approved', 'rejected' => 'Rejected', 'cancelled' => 'Cancelled', 'withdrawn' => 'Withdrawn'] as $value => $label): ?><option value="<?= e($value); ?>" <?= (string) ($status ?? 'all') === $value ? 'selected' : ''; ?>><?= e($label); ?></option><?php endforeach; ?></select></div><div class="col-md-3 col-lg-2"><label class="form-label">Leave Type</label><select name="leave_type_id" class="form-select"><option value="0">All leave types</option><?php foreach (($leaveTypes ?? []) as $leaveType): ?><option value="<?= e((string) $leaveType['id']); ?>" <?= (string) ($leaveTypeId ?? 0) === (string) $leaveType['id'] ? 'selected' : ''; ?>><?= e((string) $leaveType['name']); ?></option><?php endforeach; ?></select></div><div class="col-lg-2 d-flex gap-2"><button type="submit" class="btn btn-outline-secondary w-100">Filter</button><a href="<?= e(url('/leave/requests')); ?>" class="btn btn-outline-light border w-100">Reset</a></div></form></div></div>

<div class="card content-card"><div class="card-body p-4"><div class="d-flex justify-content-between align-items-center mb-3"><h5 class="mb-0">Request Directory</h5><div class="d-flex gap-2"><a href="<?= e(url('/leave/requests/export-excel') . '?' . http_build_query(array_filter(['q' => $search ?? '', 'status' => $status ?? '', 'leave_type_id' => $leaveTypeId ?? 0]))); ?>" class="btn btn-outline-success btn-sm"><i class="bi bi-file-earmark-excel"></i> Excel</a><a href="<?= e(url('/leave/requests/export-pdf') . '?' . http_build_query(array_filter(['q' => $search ?? '', 'status' => $status ?? '', 'leave_type_id' => $leaveTypeId ?? 0]))); ?>" class="btn btn-outline-danger btn-sm"><i class="bi bi-file-earmark-pdf"></i> PDF</a><?php if (can('leave.submit')): ?><a href="<?= e(url('/leave/request')); ?>" class="btn btn-primary btn-sm"><i class="bi bi-plus-lg"></i> Request Leave</a><?php endif; ?></div></div><?php if (($requests ?? []) === []): ?><div class="empty-state">No leave requests matched the selected filters.</div><?php else: ?><div class="table-responsive"><table class="table align-middle mb-0"><thead><tr><th>Request</th><th>Dates</th><th>Days</th><th>Status</th><th>Submitted</th><th></th></tr></thead><tbody><?php foreach ($requests as $leaveRequest): ?><tr><td><div class="fw-semibold"><?= e((string) $leaveRequest['leave_type_name']); ?></div><div class="small text-muted"><?= e((string) $leaveRequest['employee_name']); ?> · <?= e((string) $leaveRequest['employee_code']); ?></div><div class="small text-muted"><?= e((string) (($leaveRequest['department_name'] ?? null) !== null ? $leaveRequest['department_name'] : 'No department')); ?></div></td><td><div><?= e((string) $leaveRequest['start_date']); ?> → <?= e((string) $leaveRequest['end_date']); ?></div><div class="small text-muted"><?= e(ucwords(str_replace('_', ' ', (string) $leaveRequest['start_session']))); ?> / <?= e(ucwords(str_replace('_', ' ', (string) $leaveRequest['end_session']))); ?></div></td><td class="fw-semibold"><?= e(number_format((float) $leaveRequest['days_requested'], 2)); ?></td><td><?php $statusValue = (string) $leaveRequest['status']; ?><span class="badge <?= in_array($statusValue, ['approved'], true) ? 'text-bg-success' : (in_array($statusValue, ['rejected', 'cancelled', 'withdrawn'], true) ? 'text-bg-danger' : 'text-bg-warning'); ?>"><?= e(ucwords(str_replace('_', ' ', $statusValue))); ?></span></td><td><?= e((string) (($leaveRequest['submitted_at'] ?? null) !== null ? $leaveRequest['submitted_at'] : $leaveRequest['created_at'])); ?></td><td class="text-end"><a href="<?= e(url('/leave/requests/' . $leaveRequest['id'])); ?>" class="btn btn-outline-secondary btn-sm">View</a></td></tr><?php endforeach; ?></tbody></table></div><?php endif; ?></div></div>