<?php declare(strict_types=1); ?>
<?php require base_path('app/Views/partials/leave-nav.php'); ?>
<?php $statusValue = (string) ($leaveRequest['status'] ?? ''); ?>
<div class="card content-card mb-4"><div class="card-body p-4"><div class="d-flex flex-column flex-lg-row justify-content-between gap-3"><div><div class="small text-muted mb-2">Leave Request #<?= e((string) ($leaveRequest['id'] ?? '')); ?></div><h4 class="mb-1"><?= e((string) ($leaveRequest['leave_type_name'] ?? '')); ?></h4><div class="text-muted"><?= e((string) ($leaveRequest['employee_name'] ?? '')); ?> · <?= e((string) ($leaveRequest['employee_code'] ?? '')); ?></div></div><div class="text-lg-end"><span class="badge <?= in_array($statusValue, ['approved'], true) ? 'text-bg-success' : (in_array($statusValue, ['rejected', 'cancelled', 'withdrawn'], true) ? 'text-bg-danger' : 'text-bg-warning'); ?> mb-2"><?= e(ucwords(str_replace('_', ' ', $statusValue))); ?></span><div class="small text-muted"><?= e((string) ($leaveRequest['start_date'] ?? '')); ?> → <?= e((string) ($leaveRequest['end_date'] ?? '')); ?></div><div class="small text-muted">Days requested: <?= e(number_format((float) ($leaveRequest['days_requested'] ?? 0), 2)); ?></div></div></div></div></div>

<div class="row g-4 mb-4">
    <div class="col-xl-8"><div class="card content-card h-100"><div class="card-body p-4"><h5 class="mb-3">Request Details</h5><div class="row g-3 small"><div class="col-md-6"><div class="text-muted">Company</div><div class="fw-semibold"><?= e((string) ($leaveRequest['company_name'] ?? '—')); ?></div></div><div class="col-md-6"><div class="text-muted">Manager</div><div class="fw-semibold"><?= e((string) (($leaveRequest['manager_name'] ?? null) !== null && $leaveRequest['manager_name'] !== '' ? $leaveRequest['manager_name'] : '—')); ?></div></div><div class="col-md-6"><div class="text-muted">Branch</div><div class="fw-semibold"><?= e((string) (($leaveRequest['branch_name'] ?? null) !== null ? $leaveRequest['branch_name'] : '—')); ?></div></div><div class="col-md-6"><div class="text-muted">Department</div><div class="fw-semibold"><?= e((string) (($leaveRequest['department_name'] ?? null) !== null ? $leaveRequest['department_name'] : '—')); ?></div></div><div class="col-md-6"><div class="text-muted">Team</div><div class="fw-semibold"><?= e((string) (($leaveRequest['team_name'] ?? null) !== null ? $leaveRequest['team_name'] : '—')); ?></div></div><div class="col-md-6"><div class="text-muted">Job Title</div><div class="fw-semibold"><?= e((string) (($leaveRequest['job_title_name'] ?? null) !== null ? $leaveRequest['job_title_name'] : '—')); ?></div></div><div class="col-md-6"><div class="text-muted">Submitted</div><div class="fw-semibold"><?= e((string) (($leaveRequest['submitted_at'] ?? null) !== null ? $leaveRequest['submitted_at'] : '—')); ?></div></div><div class="col-md-6"><div class="text-muted">Decided</div><div class="fw-semibold"><?= e((string) (($leaveRequest['decided_at'] ?? null) !== null ? $leaveRequest['decided_at'] : '—')); ?></div></div><div class="col-md-6"><div class="text-muted">Balance Required</div><div class="fw-semibold"><?= (int) ($leaveRequest['requires_balance'] ?? 0) === 1 ? 'Yes' : 'No'; ?></div></div><div class="col-md-6"><div class="text-muted">Attachment Required</div><div class="fw-semibold"><?= (int) ($leaveRequest['requires_attachment'] ?? 0) === 1 ? 'Yes' : 'No'; ?></div></div></div><hr><h6 class="mb-2">Reason</h6><p class="mb-0"><?= nl2br(e((string) ($leaveRequest['reason'] ?? ''))); ?></p><?php if (($leaveRequest['rejection_reason'] ?? null) !== null && (string) $leaveRequest['rejection_reason'] !== ''): ?><hr><h6 class="mb-2 text-danger">Rejection Reason</h6><p class="mb-0 text-danger-emphasis"><?= nl2br(e((string) $leaveRequest['rejection_reason'])); ?></p><?php endif; ?></div></div></div>
    <div class="col-xl-4"><div class="card content-card mb-4"><div class="card-body p-4"><h5 class="mb-3">Timeline</h5><div class="small text-muted mb-2">Created</div><div class="fw-semibold mb-3"><?= e((string) (($leaveRequest['created_at'] ?? null) !== null ? $leaveRequest['created_at'] : '—')); ?></div><div class="small text-muted mb-2">Last Updated</div><div class="fw-semibold mb-3"><?= e((string) (($leaveRequest['updated_at'] ?? null) !== null ? $leaveRequest['updated_at'] : '—')); ?></div><?php if (($leaveRequest['cancelled_at'] ?? null) !== null): ?><div class="small text-muted mb-2">Cancelled</div><div class="fw-semibold mb-3"><?= e((string) $leaveRequest['cancelled_at']); ?></div><?php endif; ?><?php if (($leaveRequest['withdrawn_at'] ?? null) !== null): ?><div class="small text-muted mb-2">Withdrawn</div><div class="fw-semibold"><?= e((string) $leaveRequest['withdrawn_at']); ?></div><?php endif; ?></div></div><div class="card content-card"><div class="card-body p-4">
<?php if (($canApprove ?? false)): ?>
    <h6 class="mb-3">Take Action</h6>
    <form method="post" action="<?= e(url('/leave/' . (int) $leaveRequest['id'] . '/approve')); ?>" class="mb-2" onsubmit="return confirm('Approve this leave request?');">
        <?= csrf_field(); ?>
        <input type="hidden" name="queue" value="<?= e((string) ($approveQueue ?? 'hr')); ?>">
        <input type="hidden" name="return_to" value="<?= e(url('/leave/requests/' . (int) $leaveRequest['id'])); ?>">
        <div class="mb-2"><textarea name="comments" class="form-control form-control-sm" rows="2" placeholder="Comments (optional)"></textarea></div>
        <div class="d-grid"><button type="submit" class="btn btn-success"><i class="bi bi-check-circle"></i> Approve</button></div>
    </form>
    <form method="post" action="<?= e(url('/leave/' . (int) $leaveRequest['id'] . '/reject')); ?>" onsubmit="return confirm('Reject this leave request?');">
        <?= csrf_field(); ?>
        <input type="hidden" name="queue" value="<?= e((string) ($approveQueue ?? 'hr')); ?>">
        <input type="hidden" name="return_to" value="<?= e(url('/leave/requests/' . (int) $leaveRequest['id'])); ?>">
        <div class="mb-2"><textarea name="reason" class="form-control form-control-sm" rows="2" placeholder="Rejection reason (required)" required></textarea></div>
        <div class="d-grid"><button type="submit" class="btn btn-danger"><i class="bi bi-x-circle"></i> Reject</button></div>
    </form>
    <hr>
<?php endif; ?>
<div class="d-grid gap-2">
    <a href="<?= e(url('/leave/requests')); ?>" class="btn btn-outline-secondary">Back to Requests</a>
    <a href="<?= e(url('/leave/calendar')); ?>" class="btn btn-outline-light border">Open Calendar</a>
</div>
</div></div></div>
</div>

<div class="row g-4">
    <div class="col-xl-7"><div class="card content-card h-100"><div class="card-body p-4"><h5 class="mb-3">Approval Trail</h5><?php if (($approvalTrail ?? []) === []): ?><div class="empty-state">No approval steps have been recorded for this request yet.</div><?php else: ?><div class="table-responsive"><table class="table align-middle mb-0"><thead><tr><th>Step</th><th>Approver</th><th>Decision</th><th>Comments</th><th>Acted</th></tr></thead><tbody><?php foreach ($approvalTrail as $step): ?><tr><td>#<?= e((string) $step['step_order']); ?></td><td><div class="fw-semibold"><?= e((string) (($step['approver_name'] ?? null) !== null && $step['approver_name'] !== '' ? $step['approver_name'] : 'Pending assignment')); ?></div><div class="small text-muted"><?= e((string) (($step['manager_level'] ?? null) !== null ? $step['manager_level'] : (($step['approver_role_name'] ?? null) !== null ? $step['approver_role_name'] : ''))); ?></div></td><td><span class="badge <?= (string) $step['decision'] === 'approved' ? 'text-bg-success' : ((string) $step['decision'] === 'rejected' ? 'text-bg-danger' : 'text-bg-warning'); ?>"><?= e(ucwords(str_replace('_', ' ', (string) $step['decision']))); ?></span></td><td><?= e((string) (($step['comments'] ?? null) !== null && $step['comments'] !== '' ? $step['comments'] : '—')); ?></td><td><?= e((string) (($step['acted_at'] ?? null) !== null ? $step['acted_at'] : '—')); ?></td></tr><?php endforeach; ?></tbody></table></div><?php endif; ?></div></div></div>
    <div class="col-xl-5"><div class="card content-card h-100"><div class="card-body p-4"><h5 class="mb-3">Attachments</h5><?php if (($attachments ?? []) === []): ?><div class="empty-state">No attachments were added to this leave request.</div><?php else: ?><div class="d-grid gap-3"><?php foreach ($attachments as $attachment): ?><div class="border rounded-4 p-3"><div class="fw-semibold"><?= e((string) $attachment['original_file_name']); ?></div><div class="small text-muted"><?= e((string) (($attachment['mime_type'] ?? null) !== null ? $attachment['mime_type'] : 'Unknown type')); ?> · <?= e((string) (($attachment['file_size'] ?? null) !== null ? $attachment['file_size'] : '')); ?></div><div class="small text-muted"><?= e((string) (($attachment['created_at'] ?? null) !== null ? $attachment['created_at'] : '')); ?></div><div class="small text-muted text-break"><?= e((string) $attachment['file_path']); ?></div></div><?php endforeach; ?></div><?php endif; ?></div></div></div>
</div>