<?php declare(strict_types=1); ?>
<?php require base_path('app/Views/partials/letters-nav.php'); ?>

<div class="d-flex align-items-center gap-3 mb-4">
    <a href="<?= e(url('/letters/templates')); ?>" class="btn btn-outline-secondary btn-sm"><i class="bi bi-arrow-left"></i> Back</a>
    <div>
        <h5 class="mb-0"><?= e((string) $typeLabel); ?> — Template</h5>
        <?php if ($hasCustom): ?>
            <small class="text-success">Custom template active</small>
        <?php else: ?>
            <small class="text-muted">Using default template</small>
        <?php endif; ?>
    </div>
</div>

<div class="row g-4">
    <div class="col-xl-8">
        <div class="card content-card">
            <div class="card-body p-4">
                <form method="post" action="<?= e(url('/letters/templates/' . e((string) $letterType) . '/save')); ?>">
                    <?= csrf_field(); ?>
                    <div class="mb-3">
                        <label class="form-label fw-semibold">Letter Body</label>
                        <div class="form-text mb-2">Use the editor to format the template visually. Placeholders on the right can be inserted into the content and will be replaced when the letter is generated.</div>
                        <div class="border rounded overflow-hidden bg-white">
                            <div class="d-flex flex-wrap gap-2 p-2 border-bottom bg-light">
                                <button type="button" class="btn btn-sm btn-outline-secondary editor-action" data-command="bold"><i class="bi bi-type-bold"></i></button>
                                <button type="button" class="btn btn-sm btn-outline-secondary editor-action" data-command="italic"><i class="bi bi-type-italic"></i></button>
                                <button type="button" class="btn btn-sm btn-outline-secondary editor-action" data-command="underline"><i class="bi bi-type-underline"></i></button>
                                <button type="button" class="btn btn-sm btn-outline-secondary editor-action" data-command="insertUnorderedList"><i class="bi bi-list-ul"></i></button>
                                <button type="button" class="btn btn-sm btn-outline-secondary editor-action" data-command="insertOrderedList"><i class="bi bi-list-ol"></i></button>
                                <button type="button" class="btn btn-sm btn-outline-secondary editor-action" data-command="formatBlock" data-value="p">P</button>
                                <button type="button" class="btn btn-sm btn-outline-secondary editor-action" data-command="formatBlock" data-value="h3">H3</button>
                                <button type="button" class="btn btn-sm btn-outline-secondary editor-action" data-command="createLink" data-prompt="Enter URL">Link</button>
                                <button type="button" class="btn btn-sm btn-outline-secondary editor-action" data-command="removeFormat">Clear</button>
                            </div>
                            <div id="letterBodyVisualEditor" class="form-control border-0 rounded-0 editor-surface" contenteditable="true" spellcheck="false" aria-label="Letter body editor"></div>
                        </div>
                        <textarea id="letterBodyEditor" name="body_content" class="d-none" required><?= e((string) $body); ?></textarea>
                    </div>
                    <div class="d-flex gap-2">
                        <button type="submit" class="btn btn-primary"><i class="bi bi-check-lg"></i> Save Template</button>
                    </div>
                </form>
            </div>
        </div>
    </div>

    <div class="col-xl-4">
        <div class="card content-card mb-3">
            <div class="card-body p-4">
                <h6 class="mb-3">Available Placeholders</h6>
                <p class="text-muted small mb-3">Click any placeholder to insert it into the editor. It is also copied to the clipboard as a fallback.</p>
                <?php
                $placeholders = [
                    '{{employee_name}}'   => 'Full name',
                    '{{employee_code}}'   => 'Employee code',
                    '{{job_title}}'       => 'Job title',
                    '{{department}}'      => 'Department',
                    '{{company_name}}'    => 'Company name',
                    '{{branch}}'          => 'Branch',
                    '{{joining_date}}'    => 'Date of joining',
                    '{{employment_type}}' => 'Employment type',
                    '{{purpose}}'         => 'Purpose (from request)',
                    '{{salary_amount}}'   => 'Salary amount (formatted)',
                    '{{additional_info}}' => 'Additional info paragraph',
                    '{{ref_number}}'      => 'Reference number',
                    '{{date}}'            => 'Today\'s date',
                    '{{signer_name}}'     => 'Generated by (HR name)',
                ];
                foreach ($placeholders as $tag => $desc): ?>
                <div class="d-flex justify-content-between align-items-center mb-2">
                    <span class="text-muted small"><?= e($desc); ?></span>
                    <code class="placeholder-chip" data-placeholder="<?= e($tag); ?>" style="cursor:pointer;user-select:all;" title="Click to insert"><?= e($tag); ?></code>
                </div>
                <?php endforeach; ?>
            </div>
        </div>

        <?php if ($hasCustom): ?>
        <div class="card content-card">
            <div class="card-body p-4">
                <h6 class="mb-2">Reset to Default</h6>
                <p class="text-muted small mb-3">Discard your custom template and restore the system default.</p>
                <form method="post" action="<?= e(url('/letters/templates/' . e((string) $letterType) . '/reset')); ?>" onsubmit="return confirm('Reset to default template?');">
                    <?= csrf_field(); ?>
                    <button type="submit" class="btn btn-outline-danger btn-sm w-100"><i class="bi bi-arrow-counterclockwise"></i> Reset to Default</button>
                </form>
            </div>
        </div>
        <?php endif; ?>
    </div>
</div>

<script>
var sourceField = document.getElementById('letterBodyEditor');
var visualEditor = document.getElementById('letterBodyVisualEditor');

if (visualEditor && sourceField) {
    visualEditor.innerHTML = sourceField.value;

    var syncEditor = function() {
        sourceField.value = visualEditor.innerHTML.trim();
    };

    visualEditor.addEventListener('input', syncEditor);
    visualEditor.addEventListener('blur', syncEditor);

    document.querySelectorAll('.editor-action').forEach(function(button) {
        button.addEventListener('click', function() {
            var command = this.dataset.command;
            var value = this.dataset.value || null;

            visualEditor.focus();

            if (command === 'createLink') {
                value = window.prompt(this.dataset.prompt || 'Enter value', 'https://');
                if (!value) {
                    return;
                }
            }

            document.execCommand(command, false, value);
            syncEditor();
        });
    });

    var form = sourceField.closest('form');
    if (form) {
        form.addEventListener('submit', syncEditor);
    }
}

document.querySelectorAll('.placeholder-chip').forEach(function(chip) {
    chip.addEventListener('click', function() {
        var placeholder = this.dataset.placeholder || this.textContent;

        if (visualEditor) {
            visualEditor.focus();
            document.execCommand('insertText', false, placeholder);
            sourceField.value = visualEditor.innerHTML.trim();
        }

        if (navigator.clipboard && navigator.clipboard.writeText) {
            navigator.clipboard.writeText(placeholder).catch(function() {});
        }

        chip.style.background = '#d1fae5';
        setTimeout(function() { chip.style.background = ''; }, 800);
    });
});
</script>

<style>
.editor-surface {
    min-height: 28rem;
    padding: 1rem 1.1rem;
    line-height: 1.7;
    font-size: 1.05rem;
    overflow-y: auto;
}

.editor-surface:focus {
    outline: none;
    box-shadow: none;
}

.editor-surface p:last-child {
    margin-bottom: 0;
}
</style>
