<?php declare(strict_types=1); ?>
<?php require base_path('app/Views/partials/admin-nav.php'); ?>
<div class="row g-4">
    <div class="col-xl-4">
        <div class="card content-card h-100"><div class="card-body p-4"><h5 class="mb-2">Create Role</h5><p class="text-muted small mb-4">Add reusable roles for access control. Permissions are assigned on the next screen.</p><form method="post" action="<?= e(url('/admin/roles')); ?>"><?= csrf_field(); ?><div class="mb-3"><label class="form-label">Role Name *</label><input type="text" name="name" class="form-control" value="<?= e((string) old('name', '')); ?>" required></div><div class="mb-3"><label class="form-label">Role Code *</label><input type="text" name="code" class="form-control" value="<?= e((string) old('code', '')); ?>" placeholder="example: team_lead"></div><div class="mb-3"><label class="form-label">Description</label><textarea name="description" class="form-control" rows="4"><?= e((string) old('description', '')); ?></textarea></div><button type="submit" class="btn btn-primary w-100">Create Role</button></form></div></div>
    </div>
    <div class="col-xl-8">
        <div class="card content-card mb-4"><div class="card-body p-4"><div class="d-flex flex-column flex-md-row justify-content-between align-items-md-center gap-3"><div><h5 class="mb-1">Roles Directory</h5><p class="text-muted mb-0">Review role usage and jump directly into permission assignment.</p></div><form method="get" action="<?= e(url('/admin/roles')); ?>" class="d-flex gap-2"><input type="text" name="q" class="form-control" placeholder="Search roles..." value="<?= e((string) ($search ?? '')); ?>"><button type="submit" class="btn btn-outline-secondary">Search</button></form></div></div></div>
        <div class="card content-card"><div class="card-body p-4"><?php if (($roles ?? []) === []): ?><div class="empty-state">No roles matched the current search.</div><?php else: ?><div class="table-responsive"><table class="table align-middle mb-0"><thead><tr><th>Role</th><th>Description</th><th>Usage</th><th class="text-end">Action</th></tr></thead><tbody><?php foreach ($roles as $role): ?><tr><td><div class="fw-semibold"><?= e((string) $role['name']); ?></div><div class="small text-muted"><?= e((string) $role['code']); ?><?php if (!empty($role['is_system'])): ?> • System<?php endif; ?></div></td><td><?= e((string) ($role['description'] ?? '')); ?></td><td><div><?= e((string) ($role['user_count'] ?? 0)); ?> user(s)</div><div class="small text-muted"><?= e((string) ($role['permission_count'] ?? 0)); ?> permission(s)</div></td><td class="text-end"><a href="<?= e(url('/admin/roles/' . $role['id'] . '/permissions')); ?>" class="btn btn-sm btn-outline-primary">Permissions</a></td></tr><?php endforeach; ?></tbody></table></div><?php endif; ?></div></div>
    </div>
</div>