<?php declare(strict_types=1); ?>
<?php require base_path('app/Views/partials/reports-nav.php'); ?>
<?php
$pageHeaderTitle = 'Reports Overview';
$pageHeaderDescription = 'Track workforce movement, leave activity, expiring documents, and offboarding from one reporting surface.';
$pageHeaderChips = [
    ['label' => (($canHr ?? false) ? 'Company-wide view' : 'Direct reports view'), 'tone' => 'brand'],
    ['label' => (string) (($overview['documents_expiring_30'] ?? 0)) . ' docs expiring', 'tone' => (($overview['documents_expiring_30'] ?? 0) > 0 ? 'warning' : 'calm')],
];
require base_path('app/Views/partials/page-header.php');
?>
<div class="row g-3 mb-4">
    <div class="col-md-6 col-xl-2"><div class="card content-card h-100"><div class="card-body"><div class="text-muted small">Employees</div><div class="display-6 fw-semibold"><?= e((string) ($overview['total_employees'] ?? 0)); ?></div></div></div></div>
    <div class="col-md-6 col-xl-2"><div class="card content-card h-100"><div class="card-body"><div class="text-muted small">Active</div><div class="display-6 fw-semibold"><?= e((string) ($overview['active_employees'] ?? 0)); ?></div></div></div></div>
    <div class="col-md-6 col-xl-2"><div class="card content-card h-100"><div class="card-body"><div class="text-muted small">Joiners 30d</div><div class="display-6 fw-semibold"><?= e((string) ($overview['new_joiners_30'] ?? 0)); ?></div></div></div></div>
    <div class="col-md-6 col-xl-2"><div class="card content-card h-100"><div class="card-body"><div class="text-muted small">Pending Leave</div><div class="display-6 fw-semibold"><?= e((string) ($overview['pending_leave'] ?? 0)); ?></div></div></div></div>
    <div class="col-md-6 col-xl-2"><div class="card content-card h-100"><div class="card-body"><div class="text-muted small">Docs Expiring</div><div class="display-6 fw-semibold"><?= e((string) ($overview['documents_expiring_30'] ?? 0)); ?></div></div></div></div>
    <div class="col-md-6 col-xl-2"><div class="card content-card h-100"><div class="card-body"><div class="text-muted small">Exits 30d</div><div class="display-6 fw-semibold"><?= e((string) ($overview['upcoming_exits_30'] ?? 0)); ?></div></div></div></div>
</div>

<div class="row g-4">
    <div class="col-lg-6"><div class="card content-card h-100"><div class="card-body p-4"><div class="d-flex justify-content-between align-items-center mb-3"><h5 class="mb-0">Department Distribution</h5><span class="text-muted small"><?= ($canHr ?? false) ? 'Company-wide' : 'Direct reports'; ?></span></div><?php if (($departments ?? []) === []): ?><div class="empty-state">No department data available.</div><?php else: ?><div class="table-responsive"><table class="table align-middle mb-0"><thead><tr><th>Department</th><th class="text-end">Employees</th></tr></thead><tbody><?php foreach ($departments as $row): ?><tr><td><?= e((string) $row['department_name']); ?></td><td class="text-end fw-semibold"><?= e((string) $row['total_employees']); ?></td></tr><?php endforeach; ?></tbody></table></div><?php endif; ?></div></div></div>
    <div class="col-lg-6"><div class="card content-card h-100"><div class="card-body p-4"><h5 class="mb-3">Leave Activity (Last 180 Days)</h5><?php if (($leaveSummary ?? []) === []): ?><div class="empty-state">No leave activity found.</div><?php else: ?><div class="table-responsive"><table class="table align-middle mb-0"><thead><tr><th>Status</th><th class="text-end">Requests</th><th class="text-end">Days</th></tr></thead><tbody><?php foreach ($leaveSummary as $row): ?><tr><td><?= e(ucwords(str_replace('_', ' ', (string) $row['status']))); ?></td><td class="text-end"><?= e((string) $row['total_requests']); ?></td><td class="text-end"><?= e((string) $row['total_days']); ?></td></tr><?php endforeach; ?></tbody></table></div><?php endif; ?></div></div></div>
    <div class="col-xl-6"><div class="card content-card h-100"><div class="card-body p-4"><h5 class="mb-3">Expiring Documents (30 Days)</h5><?php if (($documentExpiry ?? []) === []): ?><div class="empty-state">No documents are due to expire in the next 30 days.</div><?php else: ?><div class="table-responsive"><table class="table align-middle mb-0"><thead><tr><th>Employee</th><th>Document</th><th>Expiry</th></tr></thead><tbody><?php foreach ($documentExpiry as $row): ?><tr><td><div class="fw-semibold"><?= e((string) $row['employee_name']); ?></div><div class="small text-muted"><?= e((string) $row['employee_code']); ?></div></td><td><div><?= e((string) $row['title']); ?></div><div class="small text-muted"><?= e((string) $row['category_name']); ?></div></td><td><div><?= e((string) $row['expiry_date']); ?></div><div class="small text-muted"><?= e((string) $row['days_until_expiry']); ?> day(s)</div></td></tr><?php endforeach; ?></tbody></table></div><?php endif; ?></div></div></div>
    <div class="col-xl-6"><div class="card content-card h-100"><div class="card-body p-4"><h5 class="mb-3">Recent Joiners</h5><?php if (($recentJoiners ?? []) === []): ?><div class="empty-state">No joiners found yet.</div><?php else: ?><div class="table-responsive"><table class="table align-middle mb-0"><thead><tr><th>Employee</th><th>Department</th><th>Joined</th></tr></thead><tbody><?php foreach ($recentJoiners as $row): ?><tr><td><div class="fw-semibold"><?= e((string) $row['employee_name']); ?></div><div class="small text-muted"><?= e((string) $row['employee_code']); ?></div></td><td><?= e((string) $row['department_name']); ?></td><td><?= e((string) $row['joining_date']); ?></td></tr><?php endforeach; ?></tbody></table></div><?php endif; ?></div></div></div>
    <div class="col-12"><div class="card content-card"><div class="card-body p-4"><h5 class="mb-3">Recent Offboarding Activity</h5><?php if (($recentExits ?? []) === []): ?><div class="empty-state">No offboarding activity recorded yet.</div><?php else: ?><div class="table-responsive"><table class="table align-middle mb-0"><thead><tr><th>Employee</th><th>Type</th><th>Exit Date</th><th>Status</th><th>Clearance</th></tr></thead><tbody><?php foreach ($recentExits as $row): ?><tr><td><div class="fw-semibold"><?= e((string) $row['employee_name']); ?></div><div class="small text-muted"><?= e((string) $row['employee_code']); ?></div></td><td><?= e(ucwords(str_replace('_', ' ', (string) $row['record_type']))); ?></td><td><?= e((string) $row['exit_date']); ?></td><td><?= e(ucwords(str_replace('_', ' ', (string) $row['status']))); ?></td><td><?= e(ucwords(str_replace('_', ' ', (string) $row['clearance_status']))); ?></td></tr><?php endforeach; ?></tbody></table></div><?php endif; ?></div></div></div>
</div>
